In [1]:
# cosmology library imports
import camb 
# import pycbc

In [2]:
# standard library imports
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from distances import distances

In [4]:
cosmo_params = {
    'redshift' : np.linspace(0,4)
}
cosmo_params

{'redshift': array([0.        , 0.08163265, 0.16326531, 0.24489796, 0.32653061,
        0.40816327, 0.48979592, 0.57142857, 0.65306122, 0.73469388,
        0.81632653, 0.89795918, 0.97959184, 1.06122449, 1.14285714,
        1.2244898 , 1.30612245, 1.3877551 , 1.46938776, 1.55102041,
        1.63265306, 1.71428571, 1.79591837, 1.87755102, 1.95918367,
        2.04081633, 2.12244898, 2.20408163, 2.28571429, 2.36734694,
        2.44897959, 2.53061224, 2.6122449 , 2.69387755, 2.7755102 ,
        2.85714286, 2.93877551, 3.02040816, 3.10204082, 3.18367347,
        3.26530612, 3.34693878, 3.42857143, 3.51020408, 3.59183673,
        3.67346939, 3.75510204, 3.83673469, 3.91836735, 4.        ])}

In [5]:
phenom_params = {
    'alpha' : 4,
    'A' : .001
}
phenom_params

{'alpha': 4, 'A': 0.001}

In [6]:
# instantiate class
dist = distances(cosmo_params, phenom_params)

In [7]:
# verify params are passed through
dist.cosmo_params

{'redshift': array([0.        , 0.08163265, 0.16326531, 0.24489796, 0.32653061,
        0.40816327, 0.48979592, 0.57142857, 0.65306122, 0.73469388,
        0.81632653, 0.89795918, 0.97959184, 1.06122449, 1.14285714,
        1.2244898 , 1.30612245, 1.3877551 , 1.46938776, 1.55102041,
        1.63265306, 1.71428571, 1.79591837, 1.87755102, 1.95918367,
        2.04081633, 2.12244898, 2.20408163, 2.28571429, 2.36734694,
        2.44897959, 2.53061224, 2.6122449 , 2.69387755, 2.7755102 ,
        2.85714286, 2.93877551, 3.02040816, 3.10204082, 3.18367347,
        3.26530612, 3.34693878, 3.42857143, 3.51020408, 3.59183673,
        3.67346939, 3.75510204, 3.83673469, 3.91836735, 4.        ])}

In [8]:
# get maximum redshift
cosmo_params['redshift'][-1]

4.0

In [9]:
# calculate lumonsity distance for given cosmo params
dist.luminosity(cosmo_params)

array([    0.        ,   360.78705836,   760.90840132,  1196.81568524,
        1665.15864193,  2162.83072748,  2686.99315443,  3235.08142307,
        3804.79895958,  4394.10215784,  5001.18039167,  5624.43370723,
        6262.45009938,  6913.98360647,  7577.93394728,  8253.32805977,
        8939.30365694,  9635.09476237, 10340.01909927, 11053.46716294,
       11774.89279037, 12503.80504192, 13239.76122148, 13982.36087728,
       14731.24064317, 15486.06979828, 16246.54643928, 17012.39417475,
       17783.35926453, 18559.20813839, 19339.72523853, 20124.71113885,
       20913.98090126, 21707.36263518, 22504.69623194, 23305.83224965,
       24110.63092825, 24918.96131697, 25730.70049971, 26545.73290521,
       27363.94969149, 28185.24819507, 29009.53143691, 29836.70767838,
       30666.69002111, 31499.39604564, 32334.74748441, 33172.66992521,
       34013.09254172, 34855.94784809])

In [10]:
dist.mod_luminosity(cosmo_params, phenom_params)

array([     0.        ,    390.84473048,    890.11888894,   1507.09127165,
         2250.29173861,   3127.52885379,   4145.93771788,   5312.04493641,
         6631.84050584,   8110.84947287,   9754.19893514,  11566.67805398,
        13552.79021817,  15716.79742772,  18062.75749075,  20594.55487175,
        23315.92609845,  26230.48060197,  29341.71778022,  32653.04097021,
        36167.76890769,  39889.14515397,  43820.34588174,  47964.48633801,
        52324.62623986,  56903.77430841,  61704.89210539,  66730.89730338,
        71984.66649493,  77469.03762431,  83186.81210936,  89140.75670721,
        95333.60516748, 101768.05970798, 108446.79234124, 115372.44607508,
       122547.63600592, 129974.95032027, 137656.95121718, 145596.175762  ,
       153795.13668026, 162256.32309889, 170982.20124085, 179975.21507841,
       189237.78694925, 198772.31813932, 208581.18943543, 218666.76165045,
       229031.37612344, 239677.35519676])

In [11]:
cosmo_params = {
    'redshift' : np.linspace(0,4),
    'E_e' : 1,
    't_e' : 1,
    't_a' : 2,
}
phenom_params = {
    'A' : 1,
    'alpha' : 4,
    'm_g' : 1,
}

In [12]:
dist.chi_term(cosmo_params, phenom_params)

array([ 0.        , -0.00411061, -0.01531671, -0.03227804, -0.05398898,
       -0.07967363, -0.10872064, -0.14064025, -0.17503465, -0.21157701,
       -0.24999601, -0.29006447, -0.33159059, -0.3744113 , -0.41838703,
       -0.46339764, -0.5093391 , -0.55612087, -0.60366384, -0.65189848,
       -0.70076351, -0.75020469, -0.80017382, -0.85062792, -0.90152857,
       -0.95284129, -1.00453507, -1.05658193, -1.10895657, -1.16163604,
       -1.21459949, -1.26782793, -1.32130401, -1.37501189, -1.42893704,
       -1.4830661 , -1.5373868 , -1.59188785, -1.6465588 , -1.70139002,
       -1.75637256, -1.81149816, -1.86675912, -1.92214831, -1.97765907,
       -2.03328521, -2.08902093, -2.14486084, -2.20079989, -2.25683333])

In [13]:
wf_params = {
        'approximant': 'TaylorF2',
        'mass1': 10,
        'mass2': 15,
        'delta_f': 1.0 / 170, 
        'f_lower': 40,
}

In [14]:
# from fisher_analysis import fisher_analysis

In [15]:
# fisher = fisher_analysis(cosmo_params, phenom_params, wf_params)

In [16]:
# fisher.generate_noise()

In [17]:
# h = fisher.get_signal()

In [18]:
# h

In [19]:
from modify_waveform import modify_waveform

In [20]:
mw = modify_waveform(cosmo_params, phenom_params, wf_params)

In [21]:
mw.lambda_A(**phenom_params)

1.0