In [1]:
# cosmology library imports
import camb 
# import pycbc

In [2]:
# standard library imports
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from distances import distances

In [4]:
cosmo_params = {
    'redshift' : np.linspace(0,4),
    'frequency': np.linspace(10e-1,10e-4)
}
cosmo_params

{'redshift': array([0.        , 0.08163265, 0.16326531, 0.24489796, 0.32653061,
        0.40816327, 0.48979592, 0.57142857, 0.65306122, 0.73469388,
        0.81632653, 0.89795918, 0.97959184, 1.06122449, 1.14285714,
        1.2244898 , 1.30612245, 1.3877551 , 1.46938776, 1.55102041,
        1.63265306, 1.71428571, 1.79591837, 1.87755102, 1.95918367,
        2.04081633, 2.12244898, 2.20408163, 2.28571429, 2.36734694,
        2.44897959, 2.53061224, 2.6122449 , 2.69387755, 2.7755102 ,
        2.85714286, 2.93877551, 3.02040816, 3.10204082, 3.18367347,
        3.26530612, 3.34693878, 3.42857143, 3.51020408, 3.59183673,
        3.67346939, 3.75510204, 3.83673469, 3.91836735, 4.        ]),
 'frequency': array([1.        , 0.97961224, 0.95922449, 0.93883673, 0.91844898,
        0.89806122, 0.87767347, 0.85728571, 0.83689796, 0.8165102 ,
        0.79612245, 0.77573469, 0.75534694, 0.73495918, 0.71457143,
        0.69418367, 0.67379592, 0.65340816, 0.63302041, 0.61263265,
        0.5922449 , 0

In [5]:
phenom_params = {
    'alpha' : 4,
    'A' : .001
}
phenom_params

{'alpha': 4, 'A': 0.001}

In [6]:
# instantiate class
dist = distances(cosmo_params, phenom_params)

In [7]:
# verify params are passed through
dist.cosmo_params

{'redshift': array([0.        , 0.08163265, 0.16326531, 0.24489796, 0.32653061,
        0.40816327, 0.48979592, 0.57142857, 0.65306122, 0.73469388,
        0.81632653, 0.89795918, 0.97959184, 1.06122449, 1.14285714,
        1.2244898 , 1.30612245, 1.3877551 , 1.46938776, 1.55102041,
        1.63265306, 1.71428571, 1.79591837, 1.87755102, 1.95918367,
        2.04081633, 2.12244898, 2.20408163, 2.28571429, 2.36734694,
        2.44897959, 2.53061224, 2.6122449 , 2.69387755, 2.7755102 ,
        2.85714286, 2.93877551, 3.02040816, 3.10204082, 3.18367347,
        3.26530612, 3.34693878, 3.42857143, 3.51020408, 3.59183673,
        3.67346939, 3.75510204, 3.83673469, 3.91836735, 4.        ]),
 'frequency': array([1.        , 0.97961224, 0.95922449, 0.93883673, 0.91844898,
        0.89806122, 0.87767347, 0.85728571, 0.83689796, 0.8165102 ,
        0.79612245, 0.77573469, 0.75534694, 0.73495918, 0.71457143,
        0.69418367, 0.67379592, 0.65340816, 0.63302041, 0.61263265,
        0.5922449 , 0

In [8]:
# get maximum redshift
cosmo_params['redshift'][-1]

4.0

In [9]:
dist.z

array([0.        , 0.08163265, 0.16326531, 0.24489796, 0.32653061,
       0.40816327, 0.48979592, 0.57142857, 0.65306122, 0.73469388,
       0.81632653, 0.89795918, 0.97959184, 1.06122449, 1.14285714,
       1.2244898 , 1.30612245, 1.3877551 , 1.46938776, 1.55102041,
       1.63265306, 1.71428571, 1.79591837, 1.87755102, 1.95918367,
       2.04081633, 2.12244898, 2.20408163, 2.28571429, 2.36734694,
       2.44897959, 2.53061224, 2.6122449 , 2.69387755, 2.7755102 ,
       2.85714286, 2.93877551, 3.02040816, 3.10204082, 3.18367347,
       3.26530612, 3.34693878, 3.42857143, 3.51020408, 3.59183673,
       3.67346939, 3.75510204, 3.83673469, 3.91836735, 4.        ])

In [10]:
# calculate lumonsity distance for given cosmo params
dist.luminosity(dist.z)

array([    0.        ,   360.78705836,   760.90840132,  1196.81568524,
        1665.15864193,  2162.83072748,  2686.99315443,  3235.08142307,
        3804.79895958,  4394.10215784,  5001.18039167,  5624.43370723,
        6262.45009938,  6913.98360647,  7577.93394728,  8253.32805977,
        8939.30365694,  9635.09476237, 10340.01909927, 11053.46716294,
       11774.89279037, 12503.80504192, 13239.76122148, 13982.36087728,
       14731.24064317, 15486.06979828, 16246.54643928, 17012.39417475,
       17783.35926453, 18559.20813839, 19339.72523853, 20124.71113885,
       20913.98090126, 21707.36263518, 22504.69623194, 23305.83224965,
       24110.63092825, 24918.96131697, 25730.70049971, 26545.73290521,
       27363.94969149, 28185.24819507, 29009.53143691, 29836.70767838,
       30666.69002111, 31499.39604564, 32334.74748441, 33172.66992521,
       34013.09254172, 34855.94784809])

In [11]:
# check D_0 term for beta method
dist.mod_luminosity(dist.z, alpha=0)

array([    0.        ,   333.72491975,   655.42301367,   965.68524795,
        1265.20339145,  1554.72741378,  1835.02985437,  2106.87801701,
        2371.01373294,  2628.1397669 ,  2878.91164603,  3123.93365778,
        3363.75788255,  3598.88531473,  3829.76832886,  4056.81393358,
        4280.38741361,  4500.81608422,  4718.39297695,  4933.38034457,
        5146.01292186,  5356.50091241,  5565.0326938 ,  5771.77724764,
        5976.88632937,  6180.49639722,  6382.73032178,  6583.69889798,
        6783.50218037,  6982.23066158,  7179.96631201,  7376.78349723,
        7572.74978773,  7767.92667409,  7962.3701993 ,  8156.13151813,
        8349.25739273,  8541.79063204,  8733.77048212,  8925.23297311,
        9116.21122816,  9306.7357389 ,  9496.83461136,  9686.53378584,
        9875.8572338 , 10064.82713438, 10253.46403288, 10441.78698325,
       10629.81367644, 10817.56055604])

In [12]:
cosmo_params = {
    'redshift' : np.linspace(0,4),
    'f_e' : 1,
    't_e' : 1,
    't_a' : 2,
}
phenom_params = {
    'A' : 1,
    'alpha' : 4,
    'lambda_g' : 1.6 * 10 ** 16,
}

In [13]:
dist.chi_term(dist.z)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
wf_params = {
        'approximant': 'TaylorF2',
        'mass1': 10,
        'mass2': 15,
        'delta_f': 1.0 / 170, 
        'f_lower': 40,
}

In [15]:
# from fisher_analysis import fisher_analysis

In [16]:
# fisher = fisher_analysis(cosmo_params, phenom_params, wf_params)

In [17]:
# fisher.generate_noise()

In [18]:
# h = fisher.get_signal()

In [19]:
# h

In [20]:
from modify_waveform import modify_waveform

In [21]:
mw = modify_waveform(cosmo_params, phenom_params, wf_params)

In [22]:
%debug
mw.u()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
mw.chirp_mass

0.0005229654387065052

In [24]:
# emitted chirp mass for z = 4
cm_e = mw.chirp_mass_e(mw.z)
cm_e

0.00010459308774130103

In [25]:
mw.m

0.24

In [26]:
mw.gr_amplitude()

/Users/michellegurevich/Desktop/gravitationalwaves/modgravity/modify_waveform.py:91: RuntimeWarning: divide by zero encountered in true_divide
  return math.sqrt(math.pi / 30) * (self.chirp_mass ** 2 / D_L)


array([           inf, 2.45306658e-10, 1.16312906e-10, 7.39491206e-11,
       5.31501715e-11, 4.09202007e-11, 3.29377346e-11, 2.73574157e-11,
       2.32610102e-11, 2.01414224e-11, 1.76965157e-11, 1.57355339e-11,
       1.41324028e-11, 1.28006476e-11, 1.16791025e-11, 1.07233672e-11,
       9.90048787e-12, 9.18553160e-12, 8.55931373e-12, 8.00685126e-12,
       7.51628648e-12, 7.07812279e-12, 6.68467248e-12, 6.32965121e-12,
       6.00787602e-12, 5.71503736e-12, 5.44752497e-12, 5.20229349e-12,
       4.97675755e-12, 4.76870925e-12, 4.57625258e-12, 4.39775095e-12,
       4.23178485e-12, 4.07711747e-12, 3.93266661e-12, 3.79748153e-12,
       3.67072383e-12, 3.55165154e-12, 3.43960583e-12, 3.33399977e-12,
       3.23430895e-12, 3.14006344e-12, 3.05084098e-12, 2.96626117e-12,
       2.88598044e-12, 2.80968776e-12, 2.73710093e-12, 2.66796335e-12,
       2.60204118e-12, 2.53912095e-12])

In [27]:
mw.modified_amplitude()

/Users/michellegurevich/Desktop/gravitationalwaves/modgravity/modify_waveform.py:95: RuntimeWarning: divide by zero encountered in power
  return EPSILON_LIGO * self.gr_amplitude() * (self.u() ** (-7 / 6))


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])